module.exports = {
    words: [
        "est capturée par le Limier",
        "refuse de lui révéler son nom",
        "est mariée de force à",
        "dans une région dévastée pour",
        "son cœur reste fidèle à",
        "l'armée des morts",
        "une puissante armée d'Immaculés",
        "vers Chateaunoir",
        "à Meereen",
        "après le massacre des Noces Pourpres",
        "l’armée des Sauvageons de Mance Rayder",
        "les Marcheurs blancs",
        "est mort",
        "est tué",
        "est trahi",
        "est empoisonné",
        "veut conquérir",
        "vers le Nord",
        "vers le Sud",
        "pour sa propre maison",
        "doit faire face à",
        "parallèlement",
        "a été formé par",
        "soudain",
        "alors que",
        "car",
        "et",
        "c'est pourquoi",
        "sont en route",
        "se retrouvent en fuite",
        "ni",
        "l'heure de la mort est la seule où l'on puisse se montrer brave",
        "il n'y a pas d'hommes tels que moi, il n'y a que moi",
        "Jon Snow",
        "le bâtard de Winterfell",
        "Sensa",
        "feu et sang",
        "jusqu’à ce que le soleil se lève à l’Ouest et se couche à l’Est",
        "je rugis",
        "les gens se prétendent volontiers affamés de vérité, mais ils la trouvent rarement à leur goût lorsqu'on la leur sert",
        "il n'était pas un dragon. Le feu ne peut pas tuer un dragon",
        "quand on joue au jeu des Tr\xF4nes, soit on gagne soit on meurt",
        "elle était du sang du dragon",
        "celui-ci n'était que le guetteur. Pendez-le en dernier, qu'il guette la mort des autres",
        "pas une Princesse, une Khaleesi",
        "tuer les Fils de la Harpie, les fils de leurs fils, et les fils des fils de leurs fils",
        "les vieilles histoires sont comme de vieux amis. […] Il faut leur rendre visite de temps à autre",
        "Dracarys",
        "Targaryen",
        "Lannister",
        "Arya",
        "Cersei",
        "le bâtard du roi Robert Baratheon",
        "explique-moi donc en quoi il est plus noble de tuer dix mille hommes au combat qu'une douzaine à table",
        "Baratheon",
        "Robert",
        "Snow",
        "Jaime",
        "le gnome",
        "Tyrion",
        "Tywin",
        "Bran",
        "le Trône de fer",
        "Westeros",
        "Essos",
        "je suis un homme du Nord",
        "ma place est ici, près de toi et non pas dans ce trou à rats qui leur sert de capitale",
        "royaume des Sept Couronnes",
        "Daenerys",
        "le roi fou",
        "Eddard",
        "trois dragons",
        "Viserys",
        "les Dothrakis",
        "l'héritier légitime",
        "sinon Khal Drogo",
        "Theon",
        "Greyjoy",
        "Ned",
        "Jorah Mormon",
        "Missandei",
        "Ver Gris",
        "Bronn",
        "Gendry",
        "Joffrey",
        "Tommen",
        "Tous les hommes devraient respecter leur parole, les rois encore d'avantage",
        "Stannis",
        "sir Davos",
        "Brienne de Torth",
        "Samwell Tarly",
        "Tormund",
        "Vère",
        "Ygritte",
        "Jeor Mormont",
        "mais un Lannister paye toujours ses dettes",
        "Varys",
        "Margeary",
        "Tyrell",
        "Shae",
        "Ramsey",
        "Bolton",
        "le Grand Moineau",
        "Littlefinger",
        "Petyr Baelish",
        "Yara",
        "Podrick",
        "Aerys",
        "main du roi",
        "la garde de nuit",
        "au-delà du Mur",
        "Port-Réal",
        "la Reine régente",
        "les Sauvageons",
        "la cité de Qarth",
        "la bannière de"
    ]
}